---
engines:
  csslint:
    enabled: true
    checks:
      gradients:
        enabled: false
  duplication:
    enabled: true
    config:
      config: .eslintrc.yml
      languages:
        - javascript
  eslint:
    enabled: true
    channel: "eslint-3"
  fixme:
    enabled: true
ratings:
  paths:
  - "src/public/js/**"
exclude_paths:
- "src/public/js/inverted.ctr.js"
- "jasmine/"
- "server.js"
